version: '3.8'

services:
  node-server:
    build:
      context: ./node_server
      dockerfile: Dockerfile
    container_name: node-server
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - projeto

  python-script:
    build:
      context: ./Scrape
      dockerfile: Dockerfile
    container_name: scrape
    depends_on:
      node-server:
        condition: service_healthy
    environment:
      - WAIT_HOSTS=node-server:4000
    networks:
      - projeto

networks:
  projeto:
    driver: bridge
